---
title: "CodeBook"
author: "Ali Mohammad Aliyar"
date: "7/14/2020"
output: html_document
---
## Getting and Cleaning the Data Set

To get ```tidySet.txt```, we do the followings:
 - Download the data from the link provided in the "Data Source" section below and unzip it into the workding directory. 
 - Run R scripts 


## Data Source 
The data are from the Human Activity Recognition Using Smartphones Data Set. A full description is available at: http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones 
The data for the project: https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip

## R Script
As assigned by the coursework, the R code file "run_analysis.R" performs the following steps: 

1. Reading in the files and merging the training and the test sets to create one data set.
1.1 Reading files
1.1.1 Reading trainings tables
1.1.2 Reading testing tables
1.1.3 Reading feature vector
1.1.4 Reading activity labels
1.2 Assigning variable names
1.3 Merging all data in one set

2. Extracting only the measurements on the mean and standard deviation for each measurement
2.1 Reading variable names
2.2 Create vector for defining ID, mean and standard deviation
2.3 Making nessesary subset from merged data set

3. Using descriptive activity names to name the activities in the data set
4. Appropriately labeling the data set with descriptive variable names
5. Creating a second, independent tidy data set with the average of each variable for each activity and each subject
5.1 Making second tidy data set
5.2 Writing second tidy data set in txt file
The code assumes all the data is present in the same folder, un-compressed and without names altered.

## Variables
```x_train```, ```y_train```, ```x_test```, ```y_test```, ```subject_train``` and s```ubject_test``` contain the data from the uncleaned downloaded files. ```x_data```, ```y_data``` and ```subject_data``` merge the previous datasets to do the required analysis. ```features``` contains the names for the ```x_data``` dataset, which are applied to the column name. 





